import {
    Activity,
    BadgeDollarSign,
    BookOpen,
    BriefcaseBusiness,
    Bug,
    Camera,
    ChartBar,
    Code2,
    CpuIcon,
    CreditCard,
    Dumbbell,
    Handshake,
    HeartPulse,
    LaptopMinimal,
    Music2,
    Palette,
    Receipt,
    Rocket,
} from "lucide-react";

export const categories = [
    {
        slug: "label",
        bgColor: "bg-[#FCE9E6]",
        iconColor: "text-[#CC522B]",
        Icon: Rocket,
        title: "Label",
        courseCount: "63476",
    },
    {
        slug: "business",
        bgColor: "bg-[#EAF0FF]",
        iconColor: "text-[#3B82F6]",
        Icon: BriefcaseBusiness,
        title: "Business",
        courseCount: "52822",
    },
    {
        slug: "finance-accounting",
        bgColor: "bg-[#FFF4E5]",
        iconColor: "text-[#F59E0B]",
        Icon: BadgeDollarSign,
        title: "Finance & Accounting",
        courseCount: "33841",
    },
    {
        slug: "it-software",
        bgColor: "bg-[#E8F7F0]",
        iconColor: "text-[#10B981]",
        Icon: Code2,
        title: "IT & Software",
        courseCount: "22649",
    },
    {
        slug: "personal-development",
        bgColor: "bg-[#F3E8FF]",
        iconColor: "text-[#8B5CF6]",
        Icon: Activity,
        title: "Personal Development",
        courseCount: "20126",
    },
    {
        slug: "office-productivity",
        bgColor: "bg-[#E0F2FE]",
        iconColor: "text-[#0EA5E9]",
        Icon: LaptopMinimal,
        title: "Office Productivity",
        courseCount: "13932",
    },
    {
        slug: "marketing",
        bgColor: "bg-[#FEF3C7]",
        iconColor: "text-[#D97706]",
        Icon: ChartBar,
        title: "Marketing",
        courseCount: "12068",
    },
    {
        slug: "photography-video",
        bgColor: "bg-[#FDE2E4]",
        iconColor: "text-[#E11D48]",
        Icon: Camera,
        title: "Photography & Video",
        courseCount: "6196",
    },
    {
        slug: "lifestyle",
        bgColor: "bg-[#DCFCE7]",
        iconColor: "text-[#16A34A]",
        Icon: BookOpen,
        title: "Lifestyle",
        courseCount: "2736",
    },
    {
        slug: "design",
        bgColor: "bg-[#F5F3FF]",
        iconColor: "text-[#7C3AED]",
        Icon: Palette,
        title: "Design",
        courseCount: "2600",
    },
    {
        slug: "health-fitness",
        bgColor: "bg-[#ECFCCB]",
        iconColor: "text-[#65A30D]",
        Icon: Dumbbell,
        title: "Health & Fitness",
        courseCount: "1678",
    },
    {
        slug: "music",
        bgColor: "bg-[#FFE4E6]",
        iconColor: "text-[#DB2777]",
        Icon: Music2,
        title: "Music",
        courseCount: "959",
    },
];